### ISSUE TITLE
HiDPi support

### ISSUE THREAD

**Issue by DChannan** [alexkay/spek#66]
Spek currently does not scale well on my 3200x1800 laptop screen, causing the frequency values to be cut off (so instead of "10kHz - 12kHz ... 22kHz" I see "0kHz - 2kHz ... 2kHz) as well as the filepath on the top of the screen.

**Comment by shapirus** [comment]
Same trouble here. I have a 3200x1800 display too, and spek doesn't seem to take the actual font size into account, squeezing it into a fixed space of a predefined size. Check the screenshot for what I mean.
Any idea of a possible workaround? Any hints as to where I could edit something in the source files and rebuild?
![spek](https://cloud.githubusercontent.com/assets/725402/12255018/432362fc-b8bd-11e5-9b8e-b0bb0bffe277.png)

**Comment by ruud-v-a** [comment]
Apart from the text being clipped, the icons in the toolbar are too small (with Gnome desktop), but the menu bar **is** scaled correctly.

**Comment by inigoval** [comment]
I have this same problem and really need it to work

anyone got a workaround??

**Comment by plawucht** [comment]
The easiest workaround: Use Spek with Wine. Just download the Windows exe, run it in wine. No scaling issues. 
But yes, I have the same problem, Gnome, no matter if Wayland or X.

**Comment by kode54** [comment]
I experience these issues on Windows when using 200% scaling, and would likely experience the same issues under Wine if my prefix is set to 192 dpi instead of the default 96.

**Comment by kode54** [comment]
Okay, I figured out how to fix this on Linux, at least. The simplest fix ever. You just have to somehow get the build scripts to set the toolkit to wxgtk3 and not wxgtk2. Easy peasy, lemon squeezy.

**Comment by alexkay** [comment]
This should be fixed on `master` with 5a331f5f923d99060befbf1a90668a507e4e2fa7, the upcoming version 0.8.6 will include the fix.

**Comment by mrclayman** [comment]
Hm, just tried the latest Git version in my Arch, but I can still see the issue happening. The thing is, though, I do remember it working previously when I tried switching from wxgtk2 to wxgtk3. Not sure why it does not work anymore now, though.

**Comment by awsms** [comment]
> Same trouble here. I have a 3200x1800 display too, and spek doesn't seem to take the actual font size into account, squeezing it into a fixed space of a predefined size. Check the screenshot for what I mean. Any idea of a possible workaround? Any hints as to where I could edit something in the source files and rebuild? ![spek](https://cloud.githubusercontent.com/assets/725402/12255018/432362fc-b8bd-11e5-9b8e-b0bb0bffe277.png)

I'm still getting this issue, as I've been for years.
